/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-09-08 07:26:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/hu97/Desktop/마이리콜%20프로젝트/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/myRecall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1681350677835L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    \n");
      out.write("    <title>마이리콜 메인페이지</title>\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"./img/logo.png\">\n");
      out.write("\n");
      out.write("    <!-- jquery cdn -->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.0.js\"\n");
      out.write("        integrity=\"sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <!--css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/footer.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/mainPage.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/login.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/signup.css\">\n");
      out.write("   \n");
      out.write("\n");
      out.write("    <!--구글 폰트 링크 -->\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div class=\"desktopContainer\">\n");
      out.write("            <div id=\"logoContainer\">\n");
      out.write("                <a href=\"\"><img id=\"mainLogo\" src=\"resources/img/logo.png\"></a>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"searchContainer\">\n");
      out.write("            	\n");
      out.write("                <div id=\"searchInput\">\n");
      out.write("                    <input  type=\"text\" placeholder=\"차량명 및 리콜사유 등을 검색해보세요!\"  />\n");
      out.write("                    <button id =\"searchInputBtn\">\n");
      out.write("                        <i class=\"fas fa-search-plus\"></i>\n");
      out.write("                    </button>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div id=\"BtnContainer\">\n");
      out.write("            	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <main>\n");
      out.write("        <!--selection 선택 후 검색하는 섹션 -->\n");
      out.write("        <section id=\"selectionSection\">\n");
      out.write("            <div id=\"container\">\n");
      out.write("\n");
      out.write("                <p>차량결함 리콜 조회 및<br>카카오톡 알림 서비스</p>\n");
      out.write("\n");
      out.write("                <div class=\"selectContainer\">\n");
      out.write("                    <select name=\"brand\" class=\"select brandSel\">\n");
      out.write("                        <option>제조사</option>\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </select>\n");
      out.write("\n");
      out.write("                    <!--https://pulpul8282.tistory.com/18  -->\n");
      out.write("                    <select name=\"car\" class=\"select carSel\">\n");
      out.write("                         <option>차량명</option>\n");
      out.write("                            \n");
      out.write("                    </select>\n");
      out.write("                    <select name=\"year\" class=\"select yearSel\">\n");
      out.write("                        <option >생산기간</option>\n");
      out.write("                    </select>\n");
      out.write("                    <button id=\"searchBtn\" type=\"submit\">검색</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- 최신 리콜 게시물 보여주는 섹션 -->\n");
      out.write("        <section id=\"newPostSection\">\n");
      out.write("            <div id=\"headLineContainer\">\n");
      out.write("                <p>최신 리콜현황</p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"newPostContainer\">\n");
      out.write("                <div class=\"newPosts\">\n");
      out.write("                    <div class=\"postImage\">\n");
      out.write("                        <img src=\"resources/img/honda.jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"postContents\">\n");
      out.write("                        <p>제작사: 혼다코리아</p>\n");
      out.write("                        <p>차명: ACCORD,CR-V</p>\n");
      out.write("                        <p>생산기간: 2003-10-06~2011-07-27</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"newPosts\">\n");
      out.write("                    <div class=\"postImage\">\n");
      out.write("                        <img src=\"resources/img/honda.jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"postContents\">\n");
      out.write("                        <p>제작사: 혼다코리아</p>\n");
      out.write("                        <p>차명: ACCORD,CR-V</p>\n");
      out.write("                        <p>생산기간: 2003-10-06~2011-07-27</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"newPosts\">\n");
      out.write("                    <div class=\"postImage\">\n");
      out.write("                        <img src=\"resources/img/honda.jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"postContents\">\n");
      out.write("                        <p>제작사: 혼다코리아</p>\n");
      out.write("                        <p>차명: ACCORD,CR-V</p>\n");
      out.write("                        <p>생산기간: 2003-10-06~2011-07-27</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"newPosts\">\n");
      out.write("                    <div class=\"postImage\">\n");
      out.write("                        <img src=\"resources/img/honda.jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"postContents\">\n");
      out.write("                        <p>제작사: 혼다코리아</p>\n");
      out.write("                        <p>차명: ACCORD,CR-V</p>\n");
      out.write("                        <p>생산기간: 2003-10-06~2011-07-27</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"newPosts\">\n");
      out.write("                    <div class=\"postImage\">\n");
      out.write("                        <img src=\"resources/img/honda.jpg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"postContents\">\n");
      out.write("                        <p>제작사:혼다코리아</p>\n");
      out.write("                        <p>차명:ACCORD,CR-V</p>\n");
      out.write("                        <p>생산기간:2003-10-06~2011-07-27</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            <!--최신게시물 next 버튼 -->\n");
      out.write("            <div id=\"nextBtnContainer\">\n");
      out.write("                <div class=\"nextBtn\">\n");
      out.write("                    <i class=\"fas fa-arrow-circle-left\"></i>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"nextBtn\">\n");
      out.write("                    <i class=\"fas fa-arrow-circle-right\"></i>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("        <!-- 로그인 버튼 클릭 시 모달로 로그인 화면 보여주는 article -->\n");
      out.write("        <article id=\"loginArticle\">\n");
      out.write("            <div id=\"loginContainer\">\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img id=\"logoImg\" src=\"resources/img/logo.png\">\n");
      out.write("                </a>\n");
      out.write("                <form id=\"loginForm\" action=\"/login\" post=\"post\">\n");
      out.write("                    <div class=\"loginInput\">\n");
      out.write("                        <input id=\"LoginidInput\" type=\"email\" placeholder=\"이메일\">\n");
      out.write("                        <input id=\"pwInput\" type=\"password\" placeholder=\"비밀번호\">\n");
      out.write("                    </div>\n");
      out.write("                    <button id=\"loginBtn\">로그인</button>\n");
      out.write("                </form>\n");
      out.write("                <p>\n");
      out.write("                    <a href=\"\">아이디 찾기</a>\n");
      out.write("                    <a href=\"\">비밀번호 찾기</a>\n");
      out.write("                    <a href=\"\">회원가입</a>\n");
      out.write("                </p>\n");
      out.write("                <div class=\"otherLoginContainer\">\n");
      out.write("                    <button id=\"googleLoginBtn\" type=\"button\"><img src=\"resources/img/googleLoginButton.png\"></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </article>\n");
      out.write("        <!-- 회원가입 버튼 클릭 시 모달로 회원가입 화면 보여주는 article -->\n");
      out.write("        <article id=\"signupArticle\">\n");
      out.write("            <div id=\"signupContainer\">\n");
      out.write("                <a href=\"\">\n");
      out.write("                    <img id=\"logoImg\" src=\"resources/img/logo.png\">\n");
      out.write("                </a>\n");
      out.write("                <form id=\"signupForm\" action=\"/signUp/register\" method=\"post\">\n");
      out.write("\n");
      out.write("                    <div class=\"inputContainer\">\n");
      out.write("                        <input id=\"SignUpidInput\" type=\"email\" placeholder=\"이메일\">\n");
      out.write("                        <button class=\"checkBtn\" id=\"emailCheckBtn\" type=\"button\">check</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"inputContainer\">\n");
      out.write("                        <input class=\"pwInput\" type=\"password\" placeholder=\"비밀번호\">\n");
      out.write("                        <input class=\"pwInput\" type=\"password\" placeholder=\"비밀번호\">\n");
      out.write("                        <button class=\"checkBtn\" id=\"pwCheckBtn\" type=\"button\">check</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"inputContainer\">\n");
      out.write("                        <input id=\"phoneNumInput\" type=\"tel\" placeholder=\"전화번호\">\n");
      out.write("                        <button class=\"checkBtn\" id=\"sendCodeBtn\" type=\"button\">send code</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"inputContainer\">\n");
      out.write("                        <input id=\"codeInput\" type=\"text\" placeholder=\"코드\">\n");
      out.write("                        <button class=\"checkBtn\"id =\"codeCheckBtn\" type=\"button\">check code</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"inputContainer\">\n");
      out.write("                        <select id=\"brandSel\">\n");
      out.write("                             <option>제조사</option>\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                        <select id=\"carSel\">\n");
      out.write("                            <option>차량명</option>\n");
      out.write("                        </select>\n");
      out.write("                        <select id=\"yearSel\">\n");
      out.write("                            <option>생산일</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <button id=\"enrollBtn\">회원가입</button>\n");
      out.write("                    <div id=\"restTime\" style=\"display: none;\"></div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </article>\n");
      out.write("    </main>\n");
      out.write("    <footer>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/login.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/signup.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/selection.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/search.js\"></script>\n");
      out.write("<script src=\"https://kit.fontawesome.com/6478f529f2.js\" crossorigin=\"anonymous\">\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("            	");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("            	\n");
          out.write("            	");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/mainPage.jsp(48,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberId==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            		<button id=\"signupBtn\">회원가입</button>\n");
          out.write("                	<button id=\"loginBtn\">로그인</button>\n");
          out.write("            	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/mainPage.jsp(52,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberId!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            		<button id =\"myPageBtn\">마이페이지</button>\n");
          out.write("            		<button id =\"logoutBtn\">로그아웃</button>\n");
          out.write("            	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mainPage.jsp(73,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mainPage.jsp(73,28) '${brands}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${brands}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mainPage.jsp(73,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("brand");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                            <option value =\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/mainPage.jsp(213,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mainPage.jsp(213,28) '${brands}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${brands}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mainPage.jsp(213,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("brand");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                            <option value =\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
